package engine.model.event.enums;

public enum EventType 
{
	EVT_MOUSE__ITEM_SELECTED_INIT,
	EVT_MOUSE__ITEM_SELECTED,
	EVT_MOUSE__ITEM_UNSELECTED_END,
	
	EVT_MOUSE__ITEM_DRAGGING_INIT,
	EVT_MOUSE__ITEM_DRAGGING,
	EVT_MOUSE__ITEM_DRAGGING_END,
	
	EVT_MOUSE__ITEM_HOVERED_INIT,
	EVT_MOUSE__ITEM_HOVERED,
	EVT_MOUSE__ITEM_HOVERED_END,
}
